#!/usr/bin/env bash
# Will attempt to execute a corda node within all subdirectories in the current working directory.

set -euo pipefail
export CAPSULE_CACHE_DIR=cache

# Allow the script to be run from outside the nodes directory.
basedir=$( dirname "$0" )
cd "$basedir"

function runnodesMac {
    # MacOS X: open each node in a in new tab.
    first=true
    script='tell app "Terminal"
    activate'
    rootdir=`pwd`
    for dir in `ls`; do
        if [ -d $dir ]; then
            cmd="bash -c 'cd $rootdir/$dir; /usr/libexec/java_home -v 1.8 --exec java -jar JAR_NAME && exit'"
            script="$script
    tell application \"System Events\" to tell process \"Terminal\" to keystroke \"t\" using command down
    delay 0.5
    do script \"$cmd\" in window 1"
            cmd="bash -c 'cd $rootdir/$dir; /usr/libexec/java_home -v 1.8 --exec java -jar JAR_NAME --webserver && exit'"
            script="$script
    tell application \"System Events\" to tell process \"Terminal\" to keystroke \"t\" using command down
    delay 0.5
    do script \"$cmd\" in window 1"
            first=false
        fi
    done
    script="$script
end tell"
    osascript -e "$script"
}

function runnodesLinux {
    # If it is set, it means that java overrides the default system java, which is what we want.
    if [ -n "${JAVA_HOME-}" ]; then
	export PATH="$JAVA_HOME/bin:$PATH"
    fi
    for dir in `ls`; do
        if [ -d $dir ]; then
            pushd $dir >/dev/null
            xterm -T "`basename $dir`" -e 'java -jar JAR_NAME' &
            xterm -T "`basename $dir`" -e 'java -jar JAR_NAME --webserver' &
            popd >/dev/null
        fi
    done
}

function runnodesWindows {
    set unixJavaHome=`cygpath ${JAVA_HOME}`
    # If it is set, it means that java overrides the default system java, which is what we want.
    if [ -n "${unixJavaHome-}" ]; then
	    export PATH="$JAVA_HOME/bin:$unixJavaHome"
    fi
    for dir in `ls`; do
        if [ -d $dir ]; then
            pushd $dir >/dev/null
            (java -jar JAR_NAME) &
            (java -jar JAR_NAME --webserver) &
            popd >/dev/null
        fi
    done
}

case "$(uname -s)" in
   Darwin)
     runnodesMac
     ;;

   Linux)
     runnodesLinux
     ;;

   CYGWIN*|MINGW32*|MSYS*)
     runnodesWindows
     ;;

   *)
     runnodesLinux
     ;;
esac